resources:
  containers:
  - container: trusty-amd64
    image: libgit2/trusty-amd64:latest
  - container: bionic-arm64
    image: libgit2/bionic-arm64:latest

trigger:
- master
- maint/*

jobs:
- job: linux_amd64_trusty_gcc_openssl
  displayName: 'Linux (amd64; Trusty; GCC; OpenSSL)'
  pool:
    vmImage: 'Ubuntu 16.04'
  container: trusty-amd64
  steps:
  - template: azure-pipelines/bash.yml
    parameters:
      environmentVariables:
        CC: gcc
        CMAKE_OPTIONS: -DUSE_HTTPS=OpenSSL -DDEPRECATED_HARD=ON
        LEAK_CHECK: valgrind

- job: linux_arm64_bionic_gcc_openssl
  displayName: 'Linux (arm64; Bionic; GCC; OpenSSL)'
  pool:
    vmImage: 'Ubuntu 16.04'
  container: bionic-arm64
  steps:
  - template: azure-pipelines/bash.yml
    parameters:
      environmentVariables:
        CC: gcc
        CMAKE_OPTIONS: -DUSE_HTTPS=OpenSSL -DDEPRECATE_HARD=ON
        RUN_INVASIVE_TESTS: true
        SKIP_PROXY_TESTS: true
